<Solution xmlns:i="http://www.w3.org/2001/XMLSchema-instance" z:Id="i1" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/" xmlns="http://schemas.datacontract.org/2004/07/NationalInstruments.PackageBuilder.Engine">
    <Name>Fgen-Scope-Plugins-Bundle</Name>
    <SourceItems>
        <SourceItem z:Id="i2">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\BuiltUI\Ni-Scope-Multirecords UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i3">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i4">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i5">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i6">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i7">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Ni-Scope-Multirecords.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i8">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Ni-Scope-Multirecords.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i9">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Ni-Scope-Multirecords.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i10">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Ni-Scope-Multirecords.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i11">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\BuiltUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i2" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i12">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i3" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i13">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i4" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i14">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i5" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i15">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i6" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i16">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i12" />
                <SourceItem z:Ref="i13" />
                <SourceItem z:Ref="i14" />
                <SourceItem z:Ref="i15" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i17">
            <PluginConfigurationOptions />
            <RelativePath>builds\Ni-Scope-Multirecords-Plugin\Ni-Scope-Multirecords</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i7" />
                <SourceItem z:Ref="i8" />
                <SourceItem z:Ref="i9" />
                <SourceItem z:Ref="i10" />
                <SourceItem z:Ref="i11" />
                <SourceItem z:Ref="i16" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
    </SourceItems>
    <InputSourceItems>
        <SourceItem z:Ref="i17" />
    </InputSourceItems>
    <Distributions>
        <Distribution z:Id="i18" i:type="Package">
            <DistributionItems>
                <DistributionItem z:Id="i19" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments</DestinationRelativePath>
                    <Name>National Instruments</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i20" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins</DestinationRelativePath>
                    <Name>Plug-Ins</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i21" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements</DestinationRelativePath>
                    <Name>Measurements</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i22" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords</DestinationRelativePath>
                    <Name>Ni-Scope-Multirecords</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i23" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Ni-Scope-Multirecords.aliases</DestinationRelativePath>
                    <Name>Ni-Scope-Multirecords.aliases</Name>
                    <SourceItem z:Ref="i7" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i24" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Ni-Scope-Multirecords.exe</DestinationRelativePath>
                    <Name>Ni-Scope-Multirecords.exe</Name>
                    <SourceItem z:Ref="i8" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i25" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Ni-Scope-Multirecords.ini</DestinationRelativePath>
                    <Name>Ni-Scope-Multirecords.ini</Name>
                    <SourceItem z:Ref="i9" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i26" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Ni-Scope-Multirecords.serviceconfig</DestinationRelativePath>
                    <Name>Ni-Scope-Multirecords.serviceconfig</Name>
                    <SourceItem z:Ref="i10" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i27" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\BuiltUI</DestinationRelativePath>
                    <Name>BuiltUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i28" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\BuiltUI\Ni-Scope-Multirecords UI.lvlibp</DestinationRelativePath>
                    <Name>Ni-Scope-Multirecords UI.lvlibp</Name>
                    <SourceItem z:Ref="i2" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i29" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i30" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i31" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i3" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i32" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i33" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i4" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i34" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i35" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i5" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i36" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i37" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Ni-Scope-Multirecords\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i6" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
            </DistributionItems>
            <Name>Scope-Multirecords-Plugin</Name>
            <OutputDirectory>Packages</OutputDirectory>
            <PluginConfigurationOptions />
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <Architecture>windows_x64</Architecture>
            <AutoIncrementVersion>Build</AutoIncrementVersion>
            <BuildStatus z:Id="i38">
                <BuildEverSuccessful>true</BuildEverSuccessful>
                <FileName>scope-multirecords-plugin_1.0.6.0_windows_x64.nipkg</FileName>
                <Version>1.0.6.0</Version>
            </BuildStatus>
            <CompanyName>MyCompany</CompanyName>
            <CustomExecutes />
            <Description>A Instrument Studio Plugin that using NI Scope to record multiple waveforms based on the trigger setting in the NI-Scope Configuration file</Description>
            <DisplayName>Scope-Multirecords-Plugin</DisplayName>
            <FileName>scope-multirecords-plugin_1.1.1.0_windows_x64.nipkg</FileName>
            <Homepage>https://github.com/NI-Measurement-Plug-Ins/scope-multirecords-plugin</Homepage>
            <MaintainerEmail>email@mycompany.com</MaintainerEmail>
            <MaintainerName>GitHub Community</MaintainerName>
            <Messages xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
            <PackageName>scope-multirecords-plugin</PackageName>
            <PackageRelationships>
                <PackageRelationship z:Id="i39">
                    <Constraint>LaterOrEqual</Constraint>
                    <DisplayName>LabVIEW Runtime (64-bit)</DisplayName>
                    <PackageName>ni-labview-2025-runtime-engine</PackageName>
                    <Relation>Depends</Relation>
                    <Version>25.3.2.49164-0+f12</Version>
                    <VersionType>AutoUpdate</VersionType>
                </PackageRelationship>
            </PackageRelationships>
            <ProductName>MyProduct-1</ProductName>
            <ReleaseNotes>Minor fix: Forget to apply timeout when fetching each record</ReleaseNotes>
            <Section>Add-Ons</Section>
            <StoreProduct>true</StoreProduct>
            <Synopsis>Scope-Multirecords-Plugin</Synopsis>
            <Version>1.1.1.0</Version>
        </Distribution>
    </Distributions>
    <Feeds />
    <DistributionGroups>
        <DistributionGroup z:Id="i40">
            <Distributions>
                <Distribution z:Ref="i18" />
            </Distributions>
            <Name>Distribution Group</Name>
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <StageDirectory>ProcessingStage</StageDirectory>
        </DistributionGroup>
    </DistributionGroups>
    <TestStandMode>true</TestStandMode>
    <PluginConfigurationOptions>
        <ConfigurationOption z:Id="i41">
            <Definition z:Id="i42">
                <Description i:nil="true" />
                <Name>TestStand Options</Name>
            </Definition>
            <HasDefaultValues>true</HasDefaultValues>
            <Value z:Id="i43" i:type="DialogConfigurationOptionValue">
                <Values>
                    <ConfigurationOptionValue z:Id="i44" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i45" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i46" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i47" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i48" i:type="StringConfigurationOptionValue">
                        <Value>SupportVIs</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i49" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i50" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i51" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i52" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i53" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i54" i:type="BooleanConfigurationOptionValue">
                        <Value>true</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i55" i:type="BooleanConfigurationOptionValue">
                        <Value>true</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i56" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i57" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i58" i:type="PathConfigurationOptionValue">
                        <RelativePath />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i59" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i60" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i61" i:type="StringConfigurationOptionValue">
                        <Value>[BootVolume]</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i62" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i63" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i64" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i65" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i66" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i67" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i68" i:type="BooleanConfigurationOptionValue" />
                </Values>
            </Value>
        </ConfigurationOption>
    </PluginConfigurationOptions>
</Solution>